<?php
require 'vendor/autoload.php';
$authenticator = new PHPGangsta_GoogleAuthenticator();

if( $_POST AND isset( $_POST['secret'] ) )
{
    $secret = $_POST['secret'];

    $otp = $_POST['otp'];//Generated by Authenticator.

    $tolerance = 0;
    			//Every otp is valid for 30 sec.
    			// If somebody provides OTP at 29th sec, by the time it reaches the server OTP is expired.
    			//So we can give tolerance =1, it will check current  & previous OTP.
    			// tolerance =2, verifies current and last two OTPS

    $checkResult = $authenticator->verifyCode($secret, $otp, $tolerance);

    if ($checkResult)
    {
        echo json_encode( ['success' => true, 'message' => 'OTP is validated succesfully' ]);
    }
    else
    {
        echo json_encode( ['success' => false, 'message' => 'Failed'] );
    }
}
else
{
    header("HTTP/1.0 404 Not Found");
    echo "<h1>404 Not Found</h1>";
    echo "The page that you have requested could not be found.";
}
